//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autodesk.Tandem.Client {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Autodesk.Tandem.Client.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASSEMBLY CODE,DESCRIPTION,LEVEL,REVIT CATEGORY,UNIFORMAT 2010,MASTERFORMAT,NOTES
        ///A,Substructure,1,,A,,
        ///A10,Foundations,2,,A10,,
        ///A1010,Standard Foundations,3,,A1010,,
        ///A1010100,Footings &amp; Pile Caps,4,-2001300,,,
        ///A1010110,Strip Footings,5,-2001300,,,
        ///A1010120,Spread Footings,5,-2001300,,,
        ///A1010130,Pile Caps,5,-2001300,A1020.70,,?
        ///A1010200,Foundation Walls,4,-2000011,A1010.10,,
        ///A1010210,Foundation Walls - CIP,5,-2000011,A1010.10,,
        ///A1010220,Foundation Walls - CMU,5,-2000011,A1010.10,,
        ///A1010230,Foundat [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AssemblyCodeToUniformat {
            get {
                return ResourceManager.GetString("AssemblyCodeToUniformat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cat_id_to_name {
            get {
                object obj = ResourceManager.GetObject("cat_id_to_name", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
